[profile.default]
optimizer = true
optimizer_runs = 4294967295 #4294967295 100000000
evm_version = 'cancun' #'cancun'
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "test-files/" }
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }